// <auto-generated />
namespace MusicCenter.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class start666 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(start666));
        
        string IMigrationMetadata.Id
        {
            get { return "201511131431307_start666"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
